config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :companies
  resources :reports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.user = current_user
    if @company.save
      redirect_to company_path(@company)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    redirect_to company_path(@company)
  end

  # this isnt working
  def destroy
    @company = Company.find(params[:id])
    if @company.destroy
      redirect_to user_path(current_user), status: :see_other
    else
      puts "Unable to delete"
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :industry, :company_house_number)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @user = current_user
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
    @company = current_user.company
  end

  def create
    @company = current_user.company
    @report = Report.new(report_params)
    @report.company = @company

    if @report.save
      redirect_to report_path(@report)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    @report.update(report_params)
    redirect_to report_path(@report)
  end

  private

  def report_params
    params.require(:report).permit(:location_country, :location_county, :start_date, :end_date, :currency, :revenue,
                                  :employee_count, :eletricity_usage, :renewables, :owned_vehicles, :quantity_vehciles,
                                  :quantity_vehicles, :office_size, :building_heating_type, :building_heating_quantity,
                                  :total_expenses, :flight_expenses, :train_expenses, :phone_computer_expenses,
                                  :legal_consultancy_expenses)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def admin
    @users = User.all
    # have not included this in the views
    @companies = Company.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def admin_users_only
    unless current_user.admin?
      redirect_to user_path(current_user), notice: "You are not permitted to access this page"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<h1>Add a company</h1>
<%= simple_form_for(@company) do |f| %>
  <%= f.input :name %>
  <%= f.input :industry %>
  <%= f.input :company_house_number %>
  <%= f.button :submit %>
<% end %>

app/views/companies/edit.html.erb
<%= render "form", company: @company %>

app/views/companies/new.html.erb
<%= render "form", company: @company  %>

app/views/companies/show.html.erb
<%= @company.name %>
<%= @company.industry %>
<%= @company.company_house_number %>

<%= link_to "Edit Company", edit_company_path(@company), class: "btn btn-primary"%>

<%# below is not workning %>
<%= link_to "Delete Company", company_path(@company), class: "btn", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>


<h1>Carbon Report</h1>

<%= link_to "Create Report", new_report_path(), class: "btn btn-primary"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarbonCalculator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
  <h1>Welcome back to Sequest, <%= @user.first_name %></h1>
  <%= link_to "Enter", user_path(current_user), class: "btn btn-primary" %>
<% else %>
  <h1>Weclome to Sequest</h1>
  <p>A free business carbon emissions calculator</p>
  <div>
    <%= link_to "Login", new_user_session_path, class: "btn btn-primary"%>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary"%>
  </div>

<% end %>

app/views/reports/_form.html.erb
<h1>Add a report</h1>
<%= simple_form_for(@report) do |f| %>
  <%= f.country_select :location_country %>
  <%= f.input :location_county %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.input :currency, priority: [ "USD - Dollar" ], collection: [ "USD - Dollar", "GBP - Pound", "EUR - Euro" ] %>
  <%= f.input :revenue %>
  <%= f.input :employee_count %>
  <%= f.input :eletricity_usage %>
  <%= f.input :renewables %>
  <%= f.input :owned_vehicles %>
  <%= f.input :quantity_vehicles %>
  <%= f.input :office_size %>
  <%= f.input :building_heating_type %>
  <%= f.input :building_heating_quantity %>
  <%= f.input :total_expenses %>
  <%= f.input :flight_expenses %>
  <%= f.input :train_expenses %>
  <%= f.input :phone_computer_expenses %>
  <%= f.input :legal_consultancy_expenses %>
  <%= f.button :submit %>
<% end %>

app/views/reports/new.html.erb
<%= render "form", report: @report %>

app/views/reports/show.html.erb
<%= @report.location_country%>
<%= @report.location_county %>
<%= @report.start_date %>
<%= @report.end_date %>
<%= @report.currency %>
<%= @report.revenue %>
<%= @report.employee_count %>
<%= @report.eletricity_usage %>
<%= @report.renewables %>
<%= @report.owned_vehicles %>
<%= @report.quantity_vehicles %>
<%= @report.office_size %>
<%= @report.building_heating_type %>
<%= @report.building_heating_quantity %>
<%= @report.total_expenses %>
<%= @report.flight_expenses %>
<%= @report.train_expenses %>
<%= @report.phone_computer_expenses %>
<%= @report.legal_consultancy_expenses %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>

      <%# inset sequest logo here %>

      <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/admin.html.erb
<% @users.each do |user| %>
  <%= user.id %>
  <%= user.first_name user.last_name %>
  <%= user.email %>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>
<p><%= @user.first_name%> <%= @user.last_name %></p>
<p><%= @user.email %></p>
<p><%= @user.created_at.mday %>/<%= @user.created_at.month %> / <%= @user.created_at.year %></p>


<h1>Company</h1>

<% if @user.company.nil? %>
  <%= link_to "Add your company", new_company_path(), class: "btn btn-primary"%>
<% else %>
  <p><%= @user.company.name %> </p>
  <p><%= @user.company.industry %></p>
  <p><%= @user.company.company_house_number %></p>
  <%= link_to "See Company", company_path(), class: "btn btn-primary"%>
<% end %>